export enum ACTION_TYPES {
  SET_CITY_WEATHER_INFO = '@@WEATHER_CITY_INFO/SET_CITY_WEATHER_INFO',
  FETCH_WEATHER_INFO = '@@WEATHER_CITY_INFO/FETCH_WEATHER',
  SET_PHOTO_CITY = '@@WEATHER_CITY_INFO/SET_PHOTO_CITY',
  FETCH_PHOTO_CITY = '@@WEATHER_CITY_INFO/FETCH_PHOTO_CITY',
}
