export enum ACTION_TYPES {
  SET_CITY = '@@BOARDS/SET_CITY',
  CREATE_LIST_SITY = '@@BOARDS/CREATE_LIST_SITY',
  SET_CITY_WEATHER = '@@BOARDS/SET_CITY_WEATHER',
  FETCH_WEATHER = '@@BOARDS/FETCH_WEATHER'
}
